[build]
  # Build command (not needed for static HTML)
  command = ""
  
  # Directory to deploy (current directory)
  publish = "."

[build.environment]
  # Node.js version (in case needed for future builds)
  NODE_VERSION = "18"

[[headers]]
  # Apply to all files
  for = "/*"
  
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache static assets for better performance
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # HTML files - shorter cache for content updates
  for = "*.html"
  
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  # CSS and JS files - longer cache with versioning
  for = "*.css"
  
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Image files - long cache
  for = "*.jpg"
  
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.mp4"
  
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules (if needed)
[[redirects]]
  from = "/index"
  to = "/"
  status = 301

# 404 fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404